### ISSUE TITLE
научить распознавать знак № в картинках

### ISSUE THREAD

**Issue by poglazov** [Upliner/textextract-test#5]
в параметрах к Tesseract, кажется, можно указать символы, которые мы ожидаем. Если таким способом не получится, то для картинок проверять в найденной строке "Счёт ... от ..." после слова Счет два-три символа отделённые пробелом (которые распознаются вместо №) и удалять их

**Comment by Upliner** [comment]
Скорее всего придётся возится с https://code.google.com/p/tesseract-ocr/wiki/TrainingTesseract3

**Comment by poglazov** [comment]
тогда чёрт с ним пока
