### ISSUE TITLE
хотя бы немного улучшить распознавание картинок

### ISSUE THREAD

**Issue by poglazov** [Upliner/textextract-test#6]
на jpg из второго набора у меня распозналось очень мало, хотя выглядят они не очень ужасно.

Способы, которые надо попробовать применить, написаны в ТЗ внизу (две статьи).

Что точно помогает: увеличение разрешения. Мой вариант: если общее разрешение (высота умножить на ширину) меньше 8 мегапикселей (соответствует A4 в 300 dpi), то imagemagick кратное увеличение, чтобы стало >8 (ключи с правильным выбором способа указаны в статье)

**Comment by Upliner** [comment]
ОК, сделал увеличение пока в питоне, потом попробую через ImageMagick
